import 'server-only';
import { randomBytes } from 'node:crypto';
import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { env } from './env';
import { PHOTO_ID_RE } from './photos/ids';

// Both IDs are generated by us (photo IDs by newPhotoId, user IDs by Better Auth), but they
// are still checked so no path is ever built from anything else.
const USER_ID_RE = /^[A-Za-z0-9_-]{1,64}$/;

export type StoredFormat = 'jpeg' | 'png' | 'webp';

const EXT: Record<StoredFormat, string> = { jpeg: 'jpg', png: 'png', webp: 'webp' };

function checkId(re: RegExp, id: string, what: string) {
  if (!re.test(id)) throw new Error(`Invalid ${what}`);
}

export function userDir(userId: string): string {
  checkId(USER_ID_RE, userId, 'user id');
  return join(env().MEDIA_ROOT, userId);
}

export function fullPath(userId: string, id: string, storedFormat: StoredFormat): string {
  checkId(PHOTO_ID_RE, id, 'photo id');
  return join(userDir(userId), `${id}.${EXT[storedFormat]}`);
}

export function thumbPath(userId: string, id: string): string {
  checkId(PHOTO_ID_RE, id, 'photo id');
  return join(userDir(userId), `${id}.thumb.webp`);
}

/** Writes bytes to a random `.tmp` file in the user's directory and returns its path. */
export async function writeTemp(userId: string, bytes: Uint8Array): Promise<string> {
  const dir = userDir(userId);
  await mkdir(dir, { recursive: true });
  const path = join(dir, `${randomBytes(12).toString('hex')}.tmp`);
  await writeFile(path, bytes, { flag: 'wx' });
  return path;
}

/** Moves a temp file into its final place atomically. */
export async function commit(tmpPath: string, finalPath: string): Promise<void> {
  await rename(tmpPath, finalPath);
}

export async function discard(tmpPaths: string[]): Promise<void> {
  await Promise.all(tmpPaths.map((p) => rm(p, { force: true })));
}
